version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: "1234567"    # Senha do usuário root
      MYSQL_DATABASE: "php-system"           # Banco de dados padrão a ser criado
      MYSQL_USER: "user"                 # Usuário customizado
      MYSQL_PASSWORD: "1234567"         # Senha do usuário customizado
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql         # Persistência dos dados
    restart: always